### ISSUE TITLE
Request for bit of documentation

### ISSUE THREAD

**Issue by chaseadam** [sabo/HarborBreeze304#2]
I stumbled across this repo which appears to do what I started reverse engineering.

What fan model were you controlling? What was the FCC ID of the transmitter of the fan?

What circuit/module are you using to transmit?

Thanks,
Adam

**Comment by sabo** [comment]
Hey Adam, thanks for taking a look.

Unfortunately, I don't live in the apartment where those particular fans are anymore, so I can't get you the exact model and FCC ID of the transmitter. I can say the remote looked exactly like the ones available on Amazon as the "Litex RCI-104" and the "Harbor Breeze CHQ8BT7098T", so my guess is that if your remote matches one of those, you're in luck.

As far as the circuit transmitter, I had to hack something together. I used an RF transmitter like [this one](https://www.sparkfun.com/products/10535), but I had to replace the resonator with something closer to the frequency that the fan was expecting. Closest I could find was one at 303.825MHz, which worked fairly well. 

I just found a few spares of the resonator I used, actually, so if you're having trouble sourcing it let me know and I'll drop a couple in the mail.

**Comment by chaseadam** [comment]
Thanks for the reply!

Looks like it is compatible with my fans, so I will give it a shot in the coming weeks.

Looks like it is a standard SAW resonator. Because I have several of the fans, I am willing to cannibalize the remote which has the right frequency. Not sure if I am going to leave the transmitter circuit as is (which is currently driven by 12v logic) or pop the resonator into a transmitter like the one you linked.

**Comment by sabo** [comment]
If you have the remote and you confirm it works for you, would you mind sending me the FCC ID and model number of the transmitter and receiver? Might as well add it to a readme
